import { CredentialsContract } from "./credentials.contract";
import { IntentContract } from "./intent.contract";


/**
 * DCDR Registry designed in the backend and consumed by DCDR server. 
 */
export interface DcdrRegistry {


  /**
   * SHA256 hash of the registry bundle (stable JSON serialization).
   * Useful as an immutable fingerprint / audit trail.
   */
  sha256: string;

  /** When the bundle was generated by the backend (ISO string). */
  generatedAt?: string;

  /**
   * Optional cryptographic signature for this registry bundle.
   *
   * Intended usage
   * - When present and valid, the runtime can treat the registry as "trusted backend-issued".
   * - This allows enabling cloud/cloud-pro capabilities while preventing a fake backend from injecting pro-only configuration.
   *
  * Signing payload
  * - Registry `sha256` string (UTF-8 bytes).
  *
  * Recommended algorithm
  * - Ed25519 signature by backend (private key) verified by runtime (embedded public key).
  * - This raises the bar against a "fake backend" serving a pro-enabled registry.
  *
  * Encoding
  * - Base64-encoded signature.
   */
  signature?: string;

  /** Optional key id / version for signature rotation (backend-defined). */
  signatureKeyId?: string;

  /** Full list of intent contracts */
  intents: IntentContract[];

  /** Full list of credential contracts */
  credentials?: CredentialsContract[];
}
